---
- name: Install the base package for admin tooling
  yum: pkg={{ openshift.common.service_type }}{{ openshift_version  }} state=present
  register: install_result

- name: Check for RPM generated config marker file .config_managed
  stat: path={{ openshift.common.config_base }}/.config_managed
  register: rpmgenerated_config

- name: Remove RPM generated config files
  file:
    path: "{{ item }}"
    state: absent
  when: openshift.common.service_type in ['atomic-openshift'] and rpmgenerated_config.stat.exists == true
  with_items:
    - "{{ openshift.common.config_base }}/master"
    - "{{ openshift.common.config_base }}/node"
    - "{{ openshift.common.config_base }}/.config_managed"

- name: Reload generated facts
  openshift_facts:

- name: Create openshift_master_config_dir if it doesn't exist
  file:
    path: "{{ openshift_master_config_dir }}"
    state: directory

- name: Create the master certificates if they do not already exist
  command: >
    {{ openshift.common.admin_binary }} create-master-certs
      --hostnames={{ openshift.common.all_hostnames | join(',') }}
      --master={{ openshift.master.api_url }}
      --public-master={{ openshift.master.public_api_url }}
      --cert-dir={{ openshift_master_config_dir }} --overwrite=false
  args:
    creates: "{{ openshift_master_config_dir }}/master.server.key"
